---
- name: Update cache.
  apt: 
    update_cache: yes

- name: Upgrade all packages.
  apt: 
    name: "*"
    state: latest

- name: Install packages.
  apt:
    name: "{{ packages }}"
    state: present

